### ISSUE TITLE
Add gas-optimized function that returns the block-starting tick to `OracleLibrary`

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v3-periphery#158]
`OracleLibrary` should contain a gas-optimized function (e.g. `consultMostRecent`) which returns the `tick` value as of the start of the current block (end of the last block).

It should first read `slot0`, then fetch `observations[slot0.observationIndex]`. If that observation was made before the current block, we can simply return `slot0.tick`. Otherwise, we need to fetch the prior observation (with the appropriate index modding), and then run the oracle calculation to return the `tick`.

Note: For the purposes of manipulation-resistance, it's almost certainly preferred to use a short-period average over this approach - however, if gas is truly at a premium and manipulation/oracle risk is appropriately constrained, this could make sense.

Note: We could also return the time since the oracle has last updated from this function, which might be another interesting/useful data point in this setting. In the case of the current observation being before the current block, it's time from then to now, otherwise 0. Note that this isn't a perfect indicator, as the oracle can update without the price changing, but it's still highly correlated. In theory, we could actually disambiguate oracle updates from price changes, but in the worst case it would require fetching every other observation, or more realistically doing a full binary search, so probably not worth it.

**Comment by sohkai** [comment]
Hey @NoahZinsmeister, I've implemented a variant of this in [`SpotOracleLibrary`](https://github.com/sohkai/uniswap-v3-spot-twap-oracle/blob/main/contracts/libraries/SpotOracleLibrary.sol).

Fetching a prior block's spot quote turned out to be harder, and much more gas-intensive, than I initially anticipated. As I expand in the [security considerations](https://github.com/sohkai/uniswap-v3-spot-twap-oracle#spot-price-is-nuanced), it is also not always the "end of last block quote", as only the first observation in a block is written to the pool. It would be more accurate to call it the "start of last block quote", with that measure also being the "end of last block quote" when there is only one trade.

> Note: For the purposes of manipulation-resistance, it's almost certainly preferred to use a short-period average over this approach - however, if gas is truly at a premium and manipulation/oracle risk is appropriately constrained, this could make sense.

I haven't done a gas benchmark, but I suspect that using a short TWAP will be much more gas efficient than trying to fetch spot when the last observation was made in the current block, and only a bit more expensive in the other case when the last observation is from a prior block, due to the amount of `CALL`s necessary to fetch spot.

In the case of the repo's ready-to-use oracle, where we wanted both spot and TWAP, it would have been maximally efficient to modify the periphery's `OracleLibrary`, specifically [these lines for querying prior seconds](https://github.com/Uniswap/uniswap-v3-periphery/blob/main/contracts/libraries/OracleLibrary.sol#L20-L25), to include a third parameter for the "short" duration TWAP.

However, short duration TWAPs are less data secure than spot because a prior intra-block transaction will write an observation, and skew the resulting short-term TWAP figure. In contrast, the spot calculated by the `SpotOracleLibrary` will always be from a historical block's observation.

> Note: We could also return the time since the oracle has last updated from this function

I didn't see a use case for this in the repo's oracle, but the most compelling reason I could think of for an oracle to want this functionality is to reject very recent prices, suspecting near-term price tampering.
